name: Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: sudo apt-get install libpcre++-dev
    - name: cmake
      run: |
        cmake -E make_directory build
        cd build
        cmake ..
    - name: Compile
      working-directory: build
      run: cmake --build . -j2
    - name: "Test paragraph-per-line"
      run: |
          ./build/test_ssplit \
            -p nonbreaking_prefixes/nonbreaking_prefix.en \
            -i tests/sample.en \
            -m p -e tests/sample.en.one_paragraph_per_line.expected
    - name: "Test one-sentence-per-line"
      run: |
          ./build/test_ssplit \
            -p nonbreaking_prefixes/nonbreaking_prefix.en \
            -i tests/sample.en \
            -m s -e tests/sample.en.one_sentence_per_line.expected
    - name: "Test wrapped-text"
      run: |
          ./build/test_ssplit \
            -p nonbreaking_prefixes/nonbreaking_prefix.en \
            -i tests/sample.en.wrapped \
            -m w -e tests/sample.en.wrapped.expected
